### ISSUE TITLE
Clicking on context menu should open up store if Windows Terminal is not installed

### ISSUE THREAD

**Issue by kameshkotwani** [Tyriar/vscode-windows-terminal#16]
I just found out that, I had recently uninstalled Windows Terminal, so after installing the extension, when I clicked on the context menu, It did nothing. In my opinion, if user has not installed Windows Terminal, it should redirect the user to the Store!

**Comment by Tyriar** [comment]
Great suggestion!

**Comment by kameshkotwani** [comment]
Wow. I am stunned. are you verified in brave publishers? so that I can tip you?

**Comment by Tyriar** [comment]
@kameshkotwani no that's fine, you can pay me back by verifying the issue 😉, v0.5.1 is out now.

**Comment by kameshkotwani** [comment]
It's working perfectly fine! Thank you :)
