### ISSUE TITLE
Publish latest version to marketplace

### ISSUE THREAD

**Issue by stuartleeks** [Tyriar/vscode-windows-terminal#26]
The latest code (with [support for devcontainers](https://github.com/Tyriar/vscode-windows-terminal/pull/24)) doesn't seem to be published to marketplace:

![image](https://user-images.githubusercontent.com/1824461/89317361-26e0b600-d675-11ea-93ac-c415ab2a8142.png)

Would be great to publish a newer version with this support :-)

**Comment by Tyriar** [comment]
Published 0.6.0, sorry about the delay

**Comment by stuartleeks** [comment]
Awesome - thank you!
