### ISSUE TITLE
Publishing `.vsix` release artifacts

### ISSUE THREAD

**Issue by filiptronicek** [Tyriar/vscode-windows-terminal#40]
Hi there👋!

It would be great if you could provide `.vsix` release artifacts in the GitHub Releases this repo publishes. I hope it wouldn't be too complex, it should be as straight forward as creating a GitHub Action, but I'd be happy to help out if anything is problematic. One could use an Action such as the one that the awesome people over at VS Code GitLens use, here it is: https://github.com/Axosoft/vscode-gitlens/blob/main/.github/workflows/cd-stable.yml.

**Comment by Tyriar** [comment]
You can download the latest vsix off the marketplace: https://marketplace.visualstudio.com/items?itemName=Tyriar.windows-terminal

**Comment by filiptronicek** [comment]
Hi, indeed we can, but I would appreciate if `.vsix` were available here too, mostly because it would make it easy to integrate into places like https://github.com/open-vsx/publish-extensions, which as you noted [you don't want to publish on yourself](https://github.com/open-vsx/publish-extensions/pull/467#issuecomment-952001578), but I'd kindly ask whether it would be possible to do this to make the process smoother for us (Microsoft doesn't allow anyone to download it from the marketplace automatically, it is unfortunately against their [Terms of Use](https://cdn.vsassets.io/v/M190_20210811.1/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf)).

**Comment by Tyriar** [comment]
@filiptronicek you're asking me to do more work when it's already trivial to just clone and build the extension manually. I push tags on a new release so it should be easy to automate on your side without adding something to the project that I don't use/can't maintain which will probably eventually break and again cause more work for me.

**Comment by filiptronicek** [comment]
@Tyriar I for sure don't want you to do work you don't see value in doing, I only wanted to reach out to discuss the possibility, so thanks for replying so quickly! I will add the extension to indeed build from source.
