### ISSUE TITLE
Windows Terminal as external fails to open wsl terminal as default

### ISSUE THREAD

**Issue by umagon** [Tyriar/vscode-windows-terminal#44]
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.70.2
- OS Version: Windows 11

Steps to Reproduce: 
1. Install windows terminal extension
2. Install Windows Terminal app.
3. Set in your settings.json:
```
    "terminal.explorerKind": "external",
    "terminal.external.windowsExec": "wt"
```
4. Configure in Windows Terminal to open default terminal "Ubuntu" (WSL).
5. Go to VS Code and press `Ctrl+Shift+C` to open external terminal. Output:
![image](https://user-images.githubusercontent.com/4467191/186530031-c31c6e74-18e8-4fb8-8036-5344308c819d.png)

What I would expect to happen is to open like this, in the current ${workspaceDirectory}:
![image](https://user-images.githubusercontent.com/4467191/186531234-cd654392-264d-4341-9c6a-331c3655af13.png)

Extension version: 0.7.0
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.79GB (1.70GB free)|
|Process Argv|--crash-reporter-id bebcbdab-92ab-48c1-81d1-99b63faaf89c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|Memory (System)|5.69GB (4.63GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30552240

```

</details>

**Comment by Tyriar** [comment]
If you're using ctrl+shift+c it's running the native VS Code issue so you would want to report at https://github.com/microsoft/vscode/issues/new

**Comment by umagon** [comment]
I already did back then. https://github.com/microsoft/vscode/issues/159430. Closing.
