### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by warpdesign** [Tyriar/vscode-windows-terminal#7]
I opened VSCode in a WSL directory, then right clicked on a folder and chose "Open in Windows Terminal" and got this error:

> Could not launch Windows Terminal: Cannot read property 'map' of undefined

- VSCode version 1.45.1
- Ubuntu-20.04 on WSL 2
- Windows Terminal 1.0.1401.0

**Comment by Tyriar** [comment]
@warpdesign are you using the preview and didn't have stable installed? This might be https://github.com/Tyriar/vscode-windows-terminal/issues/6

**Comment by warpdesign** [comment]
I'm using the stable build.

Looking at the extension code it seems it expects a list array with the profiles in the terminal json settings file:

```js
const defaultProfile = settings.profiles.list.find(p => p.guid === settings.defaultProfile)
```

Problem is in my settings file, profiles is the array containing the profiles:

> {
>   profiles: [
>            ...

I guess this explains the crash.

**Comment by Tyriar** [comment]
I guess the schema changed at one point, can add support for both 👍
